### ISSUE TITLE
Failed to activate the boot-java package

### ISSUE THREAD

**Issue by mspark7233** [spring-projects/atom-boot-java#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [boot-java](https://github.com/spring-projects/atom-boot-java) package 0.1.2

### Stack Trace

Failed to activate the boot-java package

```
At Cannot find module 'pivotal-atom-languageclient-commons'

Error: Cannot find module 'pivotal-atom-languageclient-commons'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/mspark/atom-boot-java-0.1.2/lib/main.js:2:51)
    at Object.<anonymous> (/Users/mspark/atom-boot-java-0.1.2/lib/main.js:142:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:937:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:244:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:227:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:220:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:217:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:695:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:670:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:647:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:865:36
```

### Commands

```
```

### Non-Core Packages

```
asciidoc-preview 2.10.3 
boot-java 0.1.2 
pretty-json 1.6.4 
```

**Comment by BoykoAlex** [comment]
Did you install `Boot-Java` extension for for Atom? Or have you linked it? It looks a lot like you've just used `apm link` command because inability to find `pivotal-atom-languageclient-commons` npm package comes from `pivotal-atom-languageclient-commons` missing from the `node_modules` folder. I only got that when i linked my extension to atom but forgot to run `npm install`...
